Feature/us5/blokkeren veiling
nehlis/pr-ip-eenmaalandermaal pull request #74
Opened 2020-12-17 14:25 UTC by SimonRijn

Ook hier moet even een manier verzonnen worden om de pagina opnieuw te laden zodra er een update gedaan wordt. Hier wordt wel een melding weergegeven nu maar de waarde wordt nog niet aangepast. 

NOTE:

Extra veld Active toegevoegd aan de Database zodat de beheerder zelf een Item op actief kan zetten. Staat standaard dus op 0

2020-12-18 08:07 UTC, thijmau requested changes
Netjes gewerkt, alleen die 2 kleine aanpassingen en dan werkt het

2020-12-18 08:07 UTC, thijmau commented on views/auction-users.php
> +    $AccountID = $_POST['AccountID'];
variables `camelCase`

2020-12-18 08:07 UTC, thijmau commented on views/auction-users.php
> +    echo "<meta http-equiv='refresh' content='0'>";
Router redirect

2020-12-18 12:07 UTC, niels-bosman commented
Wat is het verschil van deze PR vergeleken met de ander?

2020-12-19 12:51 UTC, thijmau approved these changes

2021-01-04 13:22 UTC, ghost approved these changes

2021-01-05 08:24 UTC, merged